### ISSUE TITLE
Incorrect date/time of classes

### ISSUE THREAD

**Issue by house92** [gomammoth/opendata#3]
The items in your classes feed (https://reports.gomammoth.co.uk/api/OpenData/Classes?afterTimestamp=0) appear to have incorrect dates when compared with the time information provided in the class title. In the example below the "ClassDays" field says "Monday", which agrees with the time string in "NextClassDate", but the "ClassName" field states that the day is Tuesday, and this is what's shown on your website. Also the time is presented as UTC when it is in fact BST.

As a side note, could the time of the class not be included in the "NextClassDate" field?

```javascript
{
    "state": "updated",
    "kind": "class",
    "id": "29",
    "modified": "3848420732",
    "data": {
        "ClassId": 29,
        "SportName": "Boxing",
        "SportId": 33,
        "ClassDays": "Monday",
        "ClassName": "Boxfit - Stockwell Tues 7.00pm",
        "ClassCapacity": 30,
        "ClassAttendees": 0,
        "ClassDuration": 60,
        "StartDate": "2015-11-01T00:00:00Z",
        "EndDate": null,
        "NextClassDate": "2017-10-16T00:00:00Z",
        "ClassTime": "1970-01-01T19:00:00Z",
        "SingleClassMembershipURL": "https://www.gomammoth.co.uk/fitness-checkout-flexible/?classid=29",
        "MultiClassMembershipURL": "https://www.gomammoth.co.uk/fitness-checkout-unlimited/?classid=29",
        "VenueName": "Stockwell (Studio)",
        "VenueId": 60,
        "VenueMapLink": "https://www.google.co.uk/maps/dir/''/1+Studley+Rd,+London+SW4+6RA/@51.4723734,-0.1238031,21z/data=!4m8!4m7!1m0!1m5!1m1!1s0x48760458afe4c9cb:0xde136378dadd9198!2m2!1d-0.1238221!2d51.4724014",
        "VenueLatitude": "51.4723734",
        "VenueLongitude": "-0.1238031",
        "VenuePointData": {
            "Geography": {
                "CoordinateSystemId": 4326,
                "WellKnownText": "POINT (-0.1238031 51.4723734)"
            }
        },
        "VenueAddress": "Stockwell Centre\r\n1 Studley Rd\r\nLondon \r\nSW4 6RA\r\n",
        "VenueDescrition": "The studio (Stockwell Centre) is a 2 minute walk from Stockwell Tube station.\r\nFrom Stockwell Tube station, turn left out of the station. Turn immediately left towards Studley Road. The Stockwell Centre should be on the left hand side. \r\n\r\n",
        "ImageURL": null,
        "VersionId": "AAAAAOViPXw=",
        "SingleClassMembershipPrice": 33,
        "MultiClassMembershipPrice": 39
    }
}
```

**Comment by gomammoth** [comment]
?

*Luke Mohr*

M      0778 968 7618
E       luke@gomammoth.co.uk
W      www.gomammoth.co.uk


THE UK'S SPORTS & SOCIAL CLUB

GO Mammoth Limited,  LU. 317 The Light Bulb, 1 Filament Walk, Wandsworth,
London, SW18 4GQ
Registered in England and Wales Company No. 7209293
*Like a Mammoth on **[image: cid:image008.png@01CF1366.4C0F3250]*
<http://www.facebook.com/gomammoth> *    Follow a Mammoth on **[image:
cid:image009.png@01CF1366.4C0F3250] <http://www.twitter.com/gomammoth>*

**Comment by house92** [comment]
I'm not sure which part of this issue you're querying, Luke. Could you please clarify?

**Comment by house92** [comment]
As an aside, I've noticed that in almost all cases the date (NextClassDate) is set to be a Sunday, so can it be assumed that the actual date of the class is the specified day (in ClassName) in the week going forward from that Sunday?
